### ISSUE TITLE
[0.25.1] HasckerDelightTestPerf test error

### ISSUE THREAD

**Issue by olebole** [cds-astro/cds-healpix-java#7]
When I run the test suite (`ant make.test`), I get the following error:
```
Testsuite: cds.healpix.common.math.HasckerDelightTestPerf
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.018 sec

Testcase: initializationError(cds.healpix.common.math.HasckerDelightTestPerf):	Caused an ERROR
Method testPerf should have no parameters
java.lang.Exception: Method testPerf should have no parameters
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)


Test cds.healpix.common.math.HasckerDelightTestPerf FAILED
```
However, the test still suceeds (exit value of ant is zero). Java version is openjdk-11.

**Comment by fxpineau** [comment]
I just fixed both issues. Thank you.
